package:
  name: vowpalwabbitds
  version: 8.4.0

source:
  git_rev: HEAD
  git_url: .
  # git_url: https://github.com/eisber/vowpal_wabbit

requirements:
  build:
    - python
    - setuptools
    - swig
    - rapidjson
    - libboost
    - libboost_program_options
    - libboost_regex
    - cmake
    - zlib
    - openssl
    - cpprest
  run:
    - python
    - cpprest
    # - libboost_program_options
    # - libboost_regex

# build:
#   include_recipe: False

about:
  home: https://github.com/JohnLangford/vowpal_wabbit
  license: BSD 3-Clause License
  license_file: LICENSE