package:
  name: vowpalwabbitds
  version: 8.4.0

source:
  git_rev: HEAD
  git_url: .
  # git_url: https://github.com/eisber/vowpal_wabbit

requirements:
  build:
    - python
    - setuptools
    - swig
    - rapidjson
    - boost-cpp
    # - libboost 1.65.1 # statiskit is b0rken
    # - libboost_program_options-dev
    # - libboost_regex-dev
    - cmake
    - zlib
    - openssl
    - cpprest
  run:
    - python
    - cpprest
    # - libboost_program_options
    # - libboost_regex

# TODO: pinning for c++
# TODO: pinning for cpprest

build:
   include_recipe: False

about:
  home: https://github.com/JohnLangford/vowpal_wabbit
  license: BSD 3-Clause License
  license_file: LICENSE